name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages-deployment"
  cancel-in-progress: false

jobs:
  # Detect which files have changed to determine if we need to deploy
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: main
          filters: |
            app:
              - 'src/**'
              - 'public/**'
              - 'package*.json'
              - 'tsconfig*.json'
              - 'vite.config.ts'
              - 'vitest.config.ts'
              - 'postcss.config.js'
              - 'tailwind.config.js'
              - 'eslint.config.js'
              - 'index.html'
              - 'components.json'
              - '.github/workflows/deploy.yml'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app == 'true' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run typecheck

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: https://koizuka.github.io/hakoiri-musume/main/
    runs-on: ubuntu-latest
    needs: [changes, build]
    if: needs.changes.outputs.app == 'true' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: dist-artifact
    
    - name: Extract build artifacts
      run: |
        cd dist-artifact
        tar -xf artifact.tar
        
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Deploy to production subdirectory
      run: |
        # Create production directory
        mkdir -p gh-pages/main
        
        # Remove existing production files
        rm -rf gh-pages/main/*
        
        # Copy new build files to production directory
        cp -r dist-artifact/* gh-pages/main/
        
        # Commit and push
        cd gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy production build from main branch"
        git push